feat: add option for git ops, print git hashes

diff --git a/common/dot-config/scripts/bash/sync-dots b/common/dot-config/scripts/bash/sync-dots
--- a/common/dot-config/scripts/bash/sync-dots
+++ b/common/dot-config/scripts/bash/sync-dots
@@ -45,45 +45,54 @@ echo "<=== Syncing dotfiles ===>"
 
 cd "$dots"
 
-LOCAL_GIT=$(git rev-parse @ 2>/dev/null)
-REMOTE_GIT=$(git rev-parse @{u} 2>/dev/null)
-BASE_GIT=$(git merge-base @ @{u} 2>/dev/null)
+read -rp "Perform Git operations? (y/n): " GIT_CONFIRM
+if [[ "$GIT_CONFIRM" =~ ^([yY]|[yY][eE][sS])$ ]]; then
+	git fetch origin main
 
-if [ -z "$LOCAL_GIT" ] || [ -z "$REMOTE_GIT" ] || [ -z "$BASE_GIT" ]; then
-	echo "Error: Could not determine Git hashes. Is the upstream set correctly?"
-	exit 1
-fi
+	LOCAL_GIT=$(git rev-parse @ 2>/dev/null)
+	REMOTE_GIT=$(git rev-parse @\{u\} 2>/dev/null)
+	BASE_GIT=$(git merge-base @ @\{u\} 2>/dev/null)
 
-if [ "$LOCAL_GIT" = "$REMOTE_GIT" ]; then
-	echo "Local and remote repositories in sync."
-elif [ "$LOCAL_GIT" = "$BASE_GIT" ]; then
-	echo "Remote has updates, commencing pull..."
-	git pull --rebase
-elif [ "$REMOTE_GIT" = "$BASE_GIT" ]; then
-	echo "Local has updates that need to be pushed."
-else
-	echo "Local and remote have diverged. Manual intervention may be required."
-fi
+	echo "LOCAL_GIT = $LOCAL_GIT"
+	echo "REMOTE_GIT = $REMOTE_GIT"
+	echo "BASE_GIT = $BASE_GIT"
 
-if [ -n "$(git status --porcelain)" ]; then
-	echo "Found local changes to commit and push..."
-	echo "Please review 'git status' and 'git diff' first:"
-	sleep 1
+	if [ -z "$LOCAL_GIT" ] || [ -z "$REMOTE_GIT" ] || [ -z "$BASE_GIT" ]; then
+		echo "Error: Could not determine Git hashes. Is the upstream set correctly?"
+		exit 1
+	fi
 
-	git status
-	read -rp "Continue? (y/n): " STATUS_CONFIRM
-	[[ "$STATUS_CONFIRM" =~ ^([yY]|[yY][eE][sS])$ ]] || exit 1
-	sleep 1
+	if [ "$LOCAL_GIT" = "$REMOTE_GIT" ]; then
+		echo "Local and remote repositories in sync."
+	elif [ "$LOCAL_GIT" = "$BASE_GIT" ]; then
+		echo "Remote has updates, commencing pull..."
+		git pull --rebase
+	elif [ "$REMOTE_GIT" = "$BASE_GIT" ]; then
+		echo "Local has updates that need to be pushed."
+	else
+		echo "Local and remote have diverged. Manual intervention may be required."
+	fi
 
-	git diff
-	read -rp "Continue? (y/n): " DIFF_CONFIRM
-	[[ "$DIFF_CONFIRM" =~ ^([yY]|[yY][eE][sS])$ ]] || exit 1
-	get_commit_msg
-	git add .
-	git commit -m "$COMMIT_MSG"
-	git push
-else
-	echo "Nothing to commit and push."
+	if [ -n "$(git status --porcelain)" ]; then
+		echo "Found local changes to commit and push..."
+		echo "Please review 'git status' and 'git diff' first:"
+		sleep 1
+
+		git status
+		read -rp "Continue? (y/n): " STATUS_CONFIRM
+		[[ "$STATUS_CONFIRM" =~ ^([yY]|[yY][eE][sS])$ ]] || exit 1
+		sleep 1
+
+		git diff
+		read -rp "Continue? (y/n): " DIFF_CONFIRM
+		[[ "$DIFF_CONFIRM" =~ ^([yY]|[yY][eE][sS])$ ]] || exit 1
+		get_commit_msg
+		git add .
+		git commit -m "$COMMIT_MSG"
+		git push
+	else
+		echo "Nothing to commit and push."
+	fi
 fi
 
 if [ "${2:-}" = "-v" ] || [ "${2:-}" = "-V" ]; then
